extends: '@waiting/eslint-config'
parserOptions:
  project: 'tsconfig.eslint.json'

rules:
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/prefer-ts-expect-error": 0

ignorePatterns:
  - fixtures
