/**
* This file is auto-generated by grpc-helper
*/

/* eslint-disable @typescript-eslint/no-namespace */

import type * as grpc from '@midwayjs/grpc'

/* package helloworld start */
export namespace helloworld {
  export interface Greeter {
    // Sends a greeting
    sayHello(data: HelloRequest): Promise<HelloReply>
    sayHello2(data: HelloRequest): Promise<HelloReply>
  }
  /**
   * Greeter client interface
   */
  export interface GreeterClient {
    // Sends a greeting
    sayHello(options?: grpc.IClientOptions): grpc.IClientUnaryService<HelloRequest, HelloReply>
    sayHello2(options?: grpc.IClientOptions): grpc.IClientUnaryService<HelloRequest, HelloReply>
  }
  export interface HelloRequest {
    id?: number
    name?: string
  }
  export interface HelloReply {
    id?: number
    message?: string
    traceId?: string
  }
}
/* package helloworld end */
